# Alumno: Miguel Benjamin Perez Suasnavar

# Bitacora de ejercicio por medio del metodo de Jacobi

## Ejercicio 1

$I. {3X_1}-{X_2}+{X_3} =1$

$II. {3X_1}+{6X_2}+{2x_3} =0$

$III. {3X_1}+{3X_2}+{7X_3} =4$

In [7]:
import numpy as np
import math 
#Se define la matriz T

T=np.array([[0,1/3,-1/3],[-3/6,0,-2/6],[-3/7,-3/7,0]])
C=np.array([1/3,0,4/7])
X=np.array([0,0,0])
print(T.shape)
print(C.shape)

error=1
while error>0.01: 
    resultado=np.dot(T,X)+C
    print("-----------------------------")
    print("*X1-----------X2----------X3")
    print(resultado)
    numerador = np.amax(abs((resultado - X)))
    denominador = np.amax(abs(resultado))
    error = numerador/denominador
    X=resultado
    print("Error: ",error)

(3, 3)
(3,)
-----------------------------
*X1-----------X2----------X3
[0.33333333 0.         0.57142857]
Error:  1.0
-----------------------------
*X1-----------X2----------X3
[ 0.14285714 -0.35714286  0.42857143]
Error:  0.8333333333333333
-----------------------------
*X1-----------X2----------X3
[ 0.07142857 -0.21428571  0.66326531]
Error:  0.35384615384615387
-----------------------------
*X1-----------X2----------X3
[ 0.04081633 -0.25680272  0.63265306]
Error:  0.06720430107526885
-----------------------------
*X1-----------X2----------X3
[ 0.03684807 -0.23129252  0.66399417]
Error:  0.047200878155872754
-----------------------------
*X1-----------X2----------X3
[ 0.03490444 -0.23975543  0.6547619 ]
Error:  0.014100185528757097
-----------------------------
*X1-----------X2----------X3
[ 0.03516089 -0.23570619  0.65922185]
Error:  0.0067654723984521626


In [2]:
print("X1=: ",resultado[0])
print("X2=: ",resultado[1])
print("X3=: ",resultado[2])

X1=:  0.03516088975272652
X2=:  -0.23570618723679945
X3=:  0.6592218520061085


## Ejercicio 2

$I.  {10X_1}-{X_2}         =9$

$II. {-X_1}+{10X_2}-{2X_3}=7$

$III.      {-2X_2}+{10X_3}=6$

In [11]:
T=np.array([[0,1/10,0],[1/10,0,2/10],[0,2/10,0]])
C=np.array([9/10,7/10,6/10])
X=np.array([0,0,0])

print(T.shape)
print(C.shape)
error=1
while error>0.01: 
    resultado=np.dot(T,X)+C
    print("-----------------------------")
    print("*X1----X2-----X3")
    print(resultado)
    numerador = np.amax(abs((resultado - X)))
    denominador = np.amax(abs(resultado))
    error = numerador/denominador
    X=resultado
    print("Error: ",error)

(3, 3)
(3,)
-----------------------------
*X1----X2-----X3
[0.9 0.7 0.6]
Error:  1.0
-----------------------------
*X1----X2-----X3
[0.97 0.91 0.74]
Error:  0.21649484536082472
-----------------------------
*X1----X2-----X3
[0.991 0.945 0.782]
Error:  0.04238143289606462
-----------------------------
*X1----X2-----X3
[0.9945 0.9555 0.789 ]
Error:  0.010558069381598858
-----------------------------
*X1----X2-----X3
[0.99555 0.95725 0.7911 ]
Error:  0.0021093867711316373


In [14]:
print("X1=: ",resultado[0])
print("X2=: ",resultado[1])
print("X3=: ",resultado[2])

X1=:  0.99555
X2=:  0.9572499999999999
X3=:  0.7911


## Ejercicio 3

$I.  {10X_1}+{5X_2}=6$

$II.  {5X_1}+{10X_2}-{4X_3}=25$

$III. {-4X_2}+{8X_3}-{X_4}=-11$

$IV. {-X_3}+{5X_4}=-11$

In [23]:
T=np.array([[0,-5/10,0,0],[-5/10,0,4/10,0],[0,4/8,0,1/8],[0,0,1/5,0]])
C=np.array([6/10,2.5,11/8,-11/5])
X=np.array([0,0,0,0])

print(T.shape)
print(C.shape)
error=1
while error>0.01: 
    resultado=np.dot(T,X)+C
    print("-----------------------------")
    print("*X1----------X2------------X3-----------X4")
    print(resultado)
    numerador = np.amax(abs((resultado - X)))
    denominador = np.amax(abs(resultado))
    error = numerador/denominador
    X=resultado
    print("Error: ",error)

(4, 4)
(4,)
-----------------------------
*X1----------X2------------X3-----------X4
[ 0.6    2.5    1.375 -2.2  ]
Error:  1.0
-----------------------------
*X1----------X2------------X3-----------X4
[-0.65   2.75   2.35  -1.925]
Error:  0.45454545454545453
-----------------------------
*X1----------X2------------X3-----------X4
[-0.775     3.765     2.509375 -1.73    ]
Error:  0.26958831341301465
-----------------------------
*X1----------X2------------X3-----------X4
[-1.2825    3.89125   3.04125  -1.698125]
Error:  0.1366848699004176
-----------------------------
*X1----------X2------------X3-----------X4
[-1.345625    4.35775     3.10835938 -1.59175   ]
Error:  0.10705065687568134
-----------------------------
*X1----------X2------------X3-----------X4
[-1.578875    4.41615625  3.35490625 -1.57832813]
Error:  0.05582838582760742
-----------------------------
*X1----------X2------------X3-----------X4
[-1.60807813  4.6314      3.38578711 -1.52901875]
Error:  0.04647487800665025
----

## Ejercicio 4

$I. {4X_1}+{X_2}-{X_3}+{X_4}=-2$

$I. {X_1}+{4X_2}-{X_3}-{X_4}=-1$

$III. {-X_1}-{X_2}+{5X_3}+{X_4}=0$

$IV. {X_1}-{X_2}+{X_3}+{3X_4}=1$

In [24]:
T=np.array([[0,-1/4,1/4,-1/4],[-1/4,0,1/4,1/4],[1/5,1/5,0,-1/5],[-1/3,1/3,-1/3,0]])
C=np.array([-2/4,-1/4,0,1/3])
X=np.array([0,0,0,0])

print(T.shape)
print(C.shape)
error=1
while error>0.01: 
    resultado=np.dot(T,X)+C
    print("-----------------------------")
    print("*X1----------X2------------X3-----------X4")
    print(resultado)
    numerador = np.amax(abs((resultado - X)))
    denominador = np.amax(abs(resultado))
    error = numerador/denominador
    X=resultado
    print("Error: ",error)

(4, 4)
(4,)
-----------------------------
*X1----------X2------------X3-----------X4
[-0.5        -0.25        0.          0.33333333]
Error:  1.0
-----------------------------
*X1----------X2------------X3-----------X4
[-0.52083333 -0.04166667 -0.21666667  0.41666667]
Error:  0.416
-----------------------------
*X1----------X2------------X3-----------X4
[-0.64791667 -0.06979167 -0.19583333  0.56527778]
Error:  0.22936763129689178
-----------------------------
*X1----------X2------------X3-----------X4
[-0.67282986  0.00434028 -0.25659722  0.59131944]
Error:  0.11017933169913562
-----------------------------
*X1----------X2------------X3-----------X4
[-0.71306424  0.00188802 -0.25196181  0.64458912]
Error:  0.07470529754296262
-----------------------------
*X1----------X2------------X3-----------X4
[-0.72460974  0.02642289 -0.27115307  0.65563802]
Error:  0.03385942205279923
-----------------------------
*X1----------X2------------X3-----------X4
[-0.73830349  0.02727367 -0.27076497  0

In [25]:
print("X1=: ",resultado[0])
print("X2=: ",resultado[1])
print("X3=: ",resultado[2])
print("X4=: ",resultado[3])

X1=:  -0.7477997903706115
X2=:  0.03619687643168884
X3=:  -0.27728114902826
X4=:  0.6851478613080311


## Ejercicios resueltos por el metodo de Newton

### Ejercicio A

${4x_1^2}-{20x_1}+{1/4x_2^2}+8=0$

${1/2X_1X_2^2}+{2x_1}-{5x_2}+8=0$

In [8]:
import numpy as np
from math import * 

def jacobiano(x):
    J = np.array([[8*x[0]-20, 1/2*x[1]], [1/2*x[1]**2, -5]])
    JInversa = np.linalg.inv(J)
    return JInversa

def Fx(x):
    xk=np.array([4*x[0]**2-20*x[0]+1/4*x[1]**2+8, 1/2*x[0]*x[1]**2+2*x[0]-5*x[1]+8]) #matriz inicial
    return xk
x = np.array([0.1, 0.1]) #vector de valores iniciales
error = 1
c=0
while error>0.01:
    c+=1
    r= jacobiano(x)
    feval = Fx(x)
    resultado =x- np.dot(r,feval)
    
    numerador = np.amax( abs((resultado - x)))
    denominador = np.amax( abs(resultado))
    error = numerador/denominador
    x=resultado
    
    print("Iteración:",c,"|Resultado ",resultado)
    

Iteración: 1 |Resultado  [0.41872505 1.64041873]
Iteración: 2 |Resultado  [0.49153376 1.89976046]
Iteración: 3 |Resultado  [0.49843679 1.97650382]
Iteración: 4 |Resultado  [0.49965555 1.99456852]


### Ejercicio C

${3x_1}-{cos}{(x_2}{x_3)}-{1/2}=0$

${4x^2_1}-{625x^2_2}+{2x_2}-1=0$

${e^-x_1x_2}+{20X_3}+10π-3/_3=0$

In [7]:
import numpy as np
from math import * 

def jacobiano(x):
    J = np.array([[3, x[2]*sin(x[1]*x[2]), x[1]*sin(x[1]*x[2])], [8, 1250*(x[1]+2), 0], [-x[1]*exp(-x[0]*x[1]), -x[0]*exp(-x[0]*x[1]), 20]])    
    JInversa = np.linalg.inv(J)
    return JInversa

def Fx(x):#matriz inicial
    xk=np.array([3*x[0]-cos(x[1]*x[2])-1/2, 4*x[0]**2-625*x[1]**2+2*x[1]-1, e**(x[0]*x[1])+20*x[2]+(10*pi-3)/(3)])
    return xk
x = np.array([0.1,0.1,-0.1]) #vector de valores iniciales
error = 1
c=0
while error>0.01:
    c+=1
    r= jacobiano(x)
    feval = Fx(x)
    resultado =x- np.dot(r,feval)
    
    numerador = np.amax( abs((resultado - x)))
    denominador = np.amax( abs(resultado))
    error = numerador/denominador
    x=resultado
    
    print("Iteración:",c,"| Resultado ",resultado)
    

Iteración: 1 | Resultado  [ 0.49984215  0.10145191 -0.52211478]
Iteración: 2 | Resultado  [ 0.4995034   0.10382484 -0.52614492]


### Ejercicio D

${X^2_1}+{X_2}-37=0$

${X_1}-{X^2_2}-5=0$

${x_1}+{X_2}+{X_3}-3=0$

In [5]:
import numpy as np
from math import * 

def jacobiano(x):
    J = np.array([[2*x[0], 1, 0], [1, -2*x[1], 0], [1, 1, 1]])
    JInversa = np.linalg.inv(J)
    return JInversa

def Fx(x): #matriz inicial
    xk=np.array([x[0]**2+x[1]-37, x[0]-x[1]**2-5, x[0]+x[1]+x[2]-3])
    return xk
x = np.array([0.1,0.1,-0.1]) #vector de valores iniciales

error = 1
c=0
while error>0.01:
    c+=1
    r= jacobiano(x)
    feval = Fx(x)
    resultado =x- np.dot(r,feval)
    
    numerador = np.amax( abs((resultado - x)))
    denominador = np.amax( abs(resultado))
    error = numerador/denominador
    x=resultado
    
    print("Iteración:",c,"| Resultado ",resultado,"|")

Iteración: 1 | Resultado  [ 11.91538462  34.62692308 -43.54230769] |
Iteración: 2 | Resultado  [  6.7827096   17.33920321 -21.12191281] |
Iteración: 3 | Resultado  [  5.47876486   8.68340745 -11.16217232] |
Iteración: 4 | Resultado  [ 5.71606289  4.3829354  -7.09899829] |
Iteración: 5 | Resultado  [ 5.89391092  2.29344398 -5.1873549 ] |
Iteración: 6 | Resultado  [ 5.97055766  1.35831592 -4.32887359] |
Iteración: 7 | Resultado  [ 5.99623096  1.04587344 -4.0421044 ] |
Iteración: 8 | Resultado  [ 5.99992047  1.00096801 -4.00088848] |
